### ISSUE TITLE
Remove capacity_providers and default_capacity_provider_strategy from configurations as they no longer exist.

### ISSUE THREAD

**Issue by Malik-Muneeb** [DNXLabs/terraform-aws-openvpn#18]
### Contact Details (optional)

munibmalik96@gmail.com

### Description. What happened?

Version 5.0.0 of the AWS provider for Terraform has removed `capacity_providers` and `default_capacity_provider_strategy` from `aws_ecs_cluster` resource. Please remove these in your next release. You can read more about it [here](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/version-5-upgrade#resourceaws_ecs_cluster)

![image](https://github.com/DNXLabs/terraform-aws-openvpn/assets/47572370/b5ca7193-0fc9-4003-8f31-3cc9256b0f8a)

### Steps to reproduce

1. Run Terraform init and then Terraform plan to reproduce it.

### Actual behavior

There shouldn't be any error in the TF plan.

### Occurrence

Frequently

### Relevant log output

```shell
╷
│ Error: Unsupported argument
│
│   on .terraform/modules/openvpn/ecs.tf line 6, in resource "aws_ecs_cluster" "ecs":
│    6:   capacity_providers = ["${var.name}-capacity-provider"]
│
│ An argument named "capacity_providers" is not expected here.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tiagoflino** [comment]
Fixed in version 1.5.0
